name: Build MT7621

on: 
  release:
    types: [published]
#  push:
#    tags:
#    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: 0 16 * * *
#  watch:
#   types: [started]

env:
  REPO_URL: https://github.com/hanwckf/rt-n56u
  REPO_BRANCH: master
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev \
        gcc-multilib
    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH rt-n56u
        cd rt-n56u/toolchain-mipsel
        ./clean_toolchain
        ./build_toolchain
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: "K2P_nano-5.0"
      run: |
        cd rt-n56u
        cwd=`pwd`
        CONFIG_TOOLCHAIN_DIR=${cwd//\//\\\/}\\/toolchain-mipsel
        cd trunk
        for m in $TNAME;
        do
        if [ ! -f configs/templates/$m.config ] ; then
        echo "configs/templates/$m.config not found "
        exit 1
        fi
        cp -f configs/templates/$m.config .config
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=y" >> .config
        sed -i "s/^CONFIG_TOOLCHAIN_DIR=.*$/CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}/g" .config
        sudo ./clear_tree_simple
        sudo ./build_firmware_bkye $m
        sudo mv -f images/*.trx /opt/images/
        done
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.R_TOKEN }}
        file: /opt/images/*.trx
        tag: AtuoBuild
        overwrite: true
        file_glob: true
    - uses: ncipollo/release-action@v1
      with:
       bodyFile: "rt-n56u/changelog.md"
       tag: AtuoBuild
       allowUpdates: true
       name: Padavan-firmware
       token: ${{ secrets.R_TOKEN }}
